<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.8.0" />
		<PackageReference Include="Grpc.Core" Version="2.46.6" />

		<!-- حذف شد: Microsoft.AspNet.Mvc -->
		<!-- حذف شد: Microsoft.AspNetCore.Razor.Runtime -->

		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.1" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />

		<PackageReference Include="MiNET" Version="1.0.2304" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />

		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RealState.BusinessLogik\RealState.BusinessLogik.csproj" />
		<ProjectReference Include="..\RealState.Dal\RealState.Dal.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\Properties\villa\" />
	</ItemGroup>

</Project>
